//
//  Room.swift
//  LiSIGN
//

import Foundation
import SwiftUI
import ModelIO

// public class Room: Identifiable {
class Room {
    private var _roomId: String = NSUUID().uuidString    // Maybe we don't need an id at all - What is the UUID type???
    private var _title: String = ""
    private var _image: String = ""
    private var _type: String = ""
    private var _roomObject: MDLAsset // MDLAsset is the type that LiDAR gives back for the 3D room scan
    
    init(title: String, image: String, type: String, roomObject: MDLAsset) {
        self._roomObject = roomObject
        // For now, the rest of the properties are hardcoded
        // self._title = "Scan 1"
        self._title = title
        // self._type = "Room"
        self._type = type
    }
    
    init(roomObject: MDLAsset) {
        self._roomObject = roomObject
        self._title = "ScannedRoom"
        self._type = "Bedroom"
        self._image = ""// image("bed3") // TODO: Replace with some image from Assets
    }
    
    public var roomId: String { // No setter for the roomId - It is autogenerated
        get {
            return self._roomId;
        }
    }
    
    public var title: String {
        get {
            return self._title;
        }
        set {
            self._title = newValue
        }
    }
    
    public var image: String {
        get {
            return self._image;
        }
        set {
            self._image = newValue
        }
    }
    
    public var type: String {
        get {
            return self._type;
        }
        set {
            self._type = newValue
        }
    }
    
    public var roomObject: MDLAsset {
        get {
            return self._roomObject;
        }
        set {
            self._roomObject = newValue
        }
    }
}

//struct Room: Decodable {
//    var title: String
//    var image: Image
//    var type: String
//    var roomObject: MDLAsset
//}

